version: '3.8'

services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: merchant_db
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database.sql:/docker-entrypoint-initdb.d/database.sql
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

  app:
    build: .
    ports:
      - "9000:9000"
    environment:
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_NAME=merchant_db
      - DB_USER=root
      - DB_PASS=password
      - NODE_ENV=development
    depends_on:
      - mysql
    volumes:
      - ./uploads:/app/uploads

volumes:
  mysql_data: 